### ISSUE TITLE
Feature: User can view all the agents, weapons and maps.

### ISSUE THREAD

**Issue by danhahn17** [danhahn17/Valorata#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Feature: User can view all the agents, weapons and maps.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view the home page and click onto the agents, weapons or maps tab. From the respective tab, the user can select an agent, weapon or map to access a new page that shows more on whatever they selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-11-28 113718](https://github.com/danhahn17/ajax-project/assets/121653016/386f9057-3431-4c84-b873-5ac8628ab3c7)
![Screenshot 2023-11-28 113701](https://github.com/danhahn17/ajax-project/assets/121653016/b12a829e-f2df-40ec-b593-db06d8c628e0)
![Screenshot 2023-11-28 113734](https://github.com/danhahn17/ajax-project/assets/121653016/2078b0e8-492a-413a-ac87-3dc23f2c46e2)
![Screenshot 2023-11-28 113744](https://github.com/danhahn17/ajax-project/assets/121653016/c1bd6d2b-6c09-4d65-9966-3e4eca767766)
![Screenshot 2023-11-28 113804](https://github.com/danhahn17/ajax-project/assets/121653016/4e36db1d-a386-47ed-ad36-a48c67c8ce4d)
![Screenshot 2023-11-28 113812](https://github.com/danhahn17/ajax-project/assets/121653016/0871bd2f-916a-48d8-bd7b-4d41324d662b)
![Screenshot 2023-11-28 113830](https://github.com/danhahn17/ajax-project/assets/121653016/a5bceae2-bd93-463d-a982-d04a2d0a9c6f)
![Screenshot 2023-11-28 113836](https://github.com/danhahn17/ajax-project/assets/121653016/f27bf863-94e2-4124-bd26-ca087889aac1)
![Screenshot 2023-11-28 113852](https://github.com/danhahn17/ajax-project/assets/121653016/e05ec55f-0770-420b-8f46-903c68582875)
![Screenshot 2023-11-28 113901](https://github.com/danhahn17/ajax-project/assets/121653016/adaca950-b2dc-4a82-98d8-ae6d5ced823c)
![Screenshot 2023-11-28 113923](https://github.com/danhahn17/ajax-project/assets/121653016/ed7c6114-7e61-4348-9242-7605758a8648)
![Screenshot 2023-11-28 113932](https://github.com/danhahn17/ajax-project/assets/121653016/d18b40a9-41b1-487e-9918-6bafec7804ef)
![Screenshot 2023-11-28 113955](https://github.com/danhahn17/ajax-project/assets/121653016/ad8e1236-d7c2-47f8-a9b1-0a7d9c631e97)
![Screenshot 2023-11-28 114003](https://github.com/danhahn17/ajax-project/assets/121653016/c9a34f1f-1764-4cf1-bb9c-e8b5248245c2)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... Create HTML:
   - [x] skeleton for homepage
   - [x] for agents tab
   - [x] for selected agent page
   - [x] for weapons tab
   - [x] for selected weapon page
   - [x] for maps tab
   - [x] for selected map page
- [x] CSS:
   - [x] for homepage
   - [x] for agents tab
   - [x] for selected agent page
   - [x] for weapons tab
   - [x] for selected weapons page
   - [x] for maps tab
   - [x] for selected map page
- [x] JavaScript:
   - [x] Query for homepage (VALORANT) and tabs (Agents, Weapons, Maps)
   - [x] Add an event listener for each tab for a click event
   - [x] Create fxn to swap between pages (makes clicked page viewable and previous page hidden)
   - [x] Query for each agent's page
   - [x] Add an event listener for each agent for a click event
   - [x] Query for each weapon's page
   - [x] Add an event listener for each weapon for a click event
   - [x] Query for each map's page
   - [x] Add an event listener for each map for a click event
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
